import SocketProvider from "@/store/socket";
import "./globals.css";
import CanvasProvider from "@/store/canvas";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <SocketProvider>
                <CanvasProvider>
                    <body className={`flex justify-center`}>{children}</body>
                </CanvasProvider>
            </SocketProvider>
        </html>
    );
}
